### PR TITLE
Add address checks when sending

### PR DESCRIPTION
**Pull request by Nasicus**
This PR basically adds the same functionality as we have in ark-desktop.
It validates the receiver address, so common mistakes can be detected.
In my opinion this is pretty important, since I read posts from a lot of people who accidentally send funds (not only Ark) to wrong addresses.

The following is implemented:

- Check if the address you're sending to is your own address
- Check if the address you're sending to doesn't have any transactions
- Check if the address you're sending to is a NEO address

I implemented it so that:

- the checks are only done, once the user clicks on send, this has  the advantage in comparison to on-type (as in desktop) that it needs to be done only once, and therefore we only have to send one/two requests in total :)
- the checks are done at the same time as the user enters his pin, therefore there should normally be no waiting time at all!

Note that the `AddressCheckerProvider` can also look for "errors" and not only "warnings", at the moment it's not really possible to have an invalid address, so there will never be an error, however it just doesn't feel right to omit this checks, therefore I added it. This way the class is also more reusable.

I also had to adjust the `pin-code.ts`. I needed to be able to keep a "state" (not on a class level) and therefore I passed in a success function (instead of specifying it on the pin code component on a class level).
  
Screenshots:

 own

empty

neo

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Hi Nasi, all looking good and working! The only thing i noticed is the first time I ran it, the Neo API took an age to respond (see below image) - I think it may be worth adding a loading icon like here: https://github.com/ArkEcosystem/ark-mobile/blob/master/src/pages/wallet/wallet-dashboard/wallet-dashboard.ts#L458-L462 just to show something is happening. What do you think? Other than the slowness and possible UX tweak, it looks good 👍 

image

**Comment by Nasicus** [comment]
@alexbarnsley totally agree. I will add something.
Also 50 seconds is unacceptable...I'll try to add a timeout limit for 30 seconds or so... it should NEVER take that long...in my tests a delay wasn't even visible. Do the requests permanently take that long for you?

**Comment by Nasicus** [comment]
- made the neo call way faster (by calling another endpoint)
- show a loading dialog if it's not finished, which looks like this;
image

**Comment by alexbarnsley** [comment]
Looking good! I'll try and test later on today or tomorrow 👌

**Comment by Nasicus** [comment]
Glad to hear it - probably will have to rebase my other PR anyway when you merge this one back, because I guess it will give merge errors ;)

**Comment by alexbarnsley** [comment]
Looking good 👍 all works as expected and faster than before!

**Pull request merged**
