### PR TITLE
Rename "Exit" to "Sign out"

### PR DESCRIPTION
**Pull request by Nasicus**
I also realized that sometimes "Logout" / "Login" and sometimes "Sign out" / "Sign in" was used. I changed this so that "Sign out" / "Sign in" is used consistently now.

@zillionn 
On Android the confirmation you talked about in your issue doesn't appear, I guess this happens only on IOS.
However I looked at the [code](https://github.com/ArkEcosystem/ark-mobile/compare/master...Nasicus:bug/sign-out?expand=1#diff-5c26d2c8f8838f32ace87fdecd6344eaR102) and it appears the correct text is used in both cases.
If it's not so: Can you describe a little more in detail when which text appears and maybe provide a screenshot?

Resolves: #83

### CODE REVIEW

**Comment by zillionn** [comment]
Pixel 2, Android 8.1.0
When I'm on the Wallets screen and tap the Android navigation back button i got this:

screenshot_20180303-164849

**Comment by Nasicus** [comment]
doesn't happen for me on OnePlus 5, Android 8.0.0.... strange.

But anyway: The message which you got is already correct right (except I replaced Logout with Sign out)?

**Comment by alexbarnsley** [comment]
@Nasicus what happens when you press the android hardware/software back button while looking at your list of wallets?

**Comment by Nasicus** [comment]
@alexbarnsley it goes back, without any confirmation.
I have a hardware back button btw.

**Comment by alexbarnsley** [comment]
@Nasicus strange - I turned on my Hardware buttons on my Oneplus 3 and they show when pressing Back on the Wallet List page 🤔 

Anyway, no problems here. Messages showing correctly. I noticed you didn't add in some of the translations for "SIGN_OUT" - presumably because you don't know them. I will allow this, as it's bound to happen at times and not everyone knows 10 languages xD

👍

**Pull request merged**
