### PR TITLE
Improvements for Watch-Only wallets

### PR DESCRIPTION
**Pull request by Nasicus**
- add possibility to manually enter address (instead of just passphrase) when importing a wallet
- add possibility to convert a watch-only to a full wallet via a wallet action
  - basically I only call the import action - if someone scans/enters a passphrase which doesn't belong to the wallet, I show an exception... I did not modify the text / possibilities in the import dialog just for this case, don't know if you find it ok this way.. (I'm  reluctant to introduce a lot of transactions which are almost never needed)
- refactor duplicated code of import pages into base class
  - the one things which changed in the logic (in one single place) is that [here](https://github.com/ArkEcosystem/ark-mobile/pull/80/files#diff-d34d011550d9de2a0689e5fb122874c0L91) only one `navCtrl` was removed and now I remove (as in all other cases) [two](https://github.com/ArkEcosystem/ark-mobile/pull/80/files#diff-d556d80b7d775dbb932537bc7b6457c3R98). I don't understand in the first place why this was differently for importing an address than when importing a a passphrase?
- introduce translateCut page, for better translations (#64)
  - I personally really like it this way, it's easy and the translations make sense this way and are not just sentence fragments (see `TYPE_PASSPHRASE_OR_KEY`)

Addresses: #79

### CODE REVIEW

**Comment by luciorubeens** [comment]
Wow, I liked the abstract class! Can you attach a screenshot?

**Comment by Nasicus** [comment]
Sure!

1. You can now enter the address instead of the passphrase when importing a wallet:



2. The added convert action & the "Watch-Only" label (whcih was before only visible in the wallet list)


3. When you choose the "convert action" you get the same screen  as when you import a new wallet (because I didn't want to add ifs & translatiosn etc.):


4. However if you enter a passphrase which doesn't belong to the watch-only wallet address, you get an exception:

**Comment by luciorubeens** [comment]
Good work! Can you resolve this conflicts?

**Comment by Nasicus** [comment]
done

**Pull request merged**
