### PR TITLE
Fix tslint & editor warnings

### PR DESCRIPTION
**Pull request by Nasicus**
Realized we had a lot of tslint errors and (in webstorm) also a lot of editor warnings.

Basically I fixed all tslint errors and the editor warnings which seemed appropriate for me.

Few things which I saw but didn't (always) change:

- should we leave unused methods in code?
- method definitions are sometimes `public` and have a return type `void` and sometimes this default values are ommitted - what do you prefer? If you want I can unifythis everywhere
- I thought if it would be nice to introduce life-time interfaces (similar to `OnInit, OnDestroy` etc. for angular) from the IONIC life cycle events - to make the code/meaning clearer? However IONIC doesn't offer these interface, so we would have to create them ourselves...what do you think about that?

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Sorry @Nasicus, there's now a conflict. Would you mind fixing please before I give it a test?

You'll become an expert at these conflicts 😉

**Comment by alexbarnsley** [comment]
@luciorubeens do you have any thoughts on @Nasicus's questions?

**Comment by Nasicus** [comment]
@alexbarnsley done... this was an easy one - I'm already used to the hardstuff :trollface:

**Comment by luciorubeens** [comment]
- It's better to comment as deprecated, and in the next versions we can remove completely.
- Yes, please unify that.
- I thinks it's unnecessary, since the ionic lifecycle is inherited from NavController.

Good job, thanks! 👍🏻

**Pull request merged**
