### PR TITLE
Passphrase bip39 word suggestions

### PR DESCRIPTION
**Pull request by air1one**
So here is a 1st version for passphrase word suggestion (#126).

- Suggesting only for last word of passphrase, and only when adding or removing one letter (not acting on copy-pasting words, neither if you want to insert or change a word which is inside the passphrase) : for simplicity and avoiding bugs or bad user experience (I did not want to check / play with cursor position)
- Word suggestion starts from 2 letters (type 'a' => no suggestion, type 'ax' => 'axis' suggested)
- Word suggested are shown in the footer above 'import' button, so they are shown above everything even when keyboard is shown
- Only suggesting in English right now (I will improve on this after, and apply this to bip39 validation too)

I went through a lot of pain to keep the textarea input focused when clicking on the suggested words. I finally found that using 'blur' event worked better than trying with button 'click' (and 'mousedown' and 'touchstart' etc).

Looking forward to hear what you think, there are probably things to rework.

### CODE REVIEW

**Comment by zillionn** [comment]
If the word is `input type=text` is the keyboard closing?

**Comment by air1one** [comment]
No luck with input type=text ; but it looks like putting the words inside a different ion-row could work.

**Comment by luciorubeens** [comment]
@air1one Good catch! Buut, this causes some weird behavior on iOS.

**Comment by air1one** [comment]
@luciorubeens you mean the image which is not hiding when the keyboard is up right ? Can you check with my last commit ?

**Comment by luciorubeens** [comment]
Great! Thank you :+1:

**Pull request merged**
