### PR TITLE
korean translation

### PR DESCRIPTION
**Pull request by infinitytn**
new kor.json

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I'll quote @ItsANameToo from #110 (except for the Korean translation):

>Don't forget to add Bulgarian to the list of available languages in src/providers/settings-data/settings-data.ts 😄

**Comment by infinitytn** [comment]
oh plz add the config as well :)

**Comment by alexbarnsley** [comment]
in case it wasn't clear, you need to add Korean here: 

https://github.com/ArkEcosystem/ark-mobile/blob/master/src/providers/settings-data/settings-data.ts#L23-L30

I will test once you've done that

**Comment by infinitytn** [comment]
i think its done now?

**Comment by alexbarnsley** [comment]
Looks good and all working! 👍

**Comment by boldninja** [comment]
@infinitytn provide me with your ARK address or contact me on Ark slack (boldninja) if you don't want to share it publicly.

**Comment by infinitytn** [comment]
@boldninja AZHsCdMyw9p5k2LPbB5NWSigf5AvktX54U here we go

**Pull request merged**
