### PR TITLE
Some typos fixed in Swedish translation

### PR DESCRIPTION
**Pull request by LgLinus**
Found some minor typos in the Swedish translation.

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Can't validate because I don't know Swedish xD +$10!

**Comment by LgLinus** [comment]
Should I post my Ark address?

ASuyj779EMAf8iLr5QJbbZ7G3JtdaBhq1j

**Comment by boldninja** [comment]
Sent

**Comment by LgLinus** [comment]
Hi!

I have a question regarding the bounty program:

In this paragraph:


*Each accepted pull request from our development team will automatically
reward you with $10 USD.*
We value your time and energy finding areas for improvement within our
code, no matter how big they are. While this is a small amount of ARK, the
pull rewards can add up over time, and each one (note that typo
pull-requests will only count once per month, per user) will automatically
enter you into the second phase of our program — monthly bounties!

--

The way I interpeted it was that "typo pull-requests" will give maximum $10
USD per month per user, but you would qualify for the monthly bounty
bonuses. Is this correct? If so, do you automatically give $50 for everyone
who is at place 7+ or how does that work? ^^

It doesn't really matter much to me since it's small amounts of money, but
if this is not the case I think it would be a good idea to be more clear
about it :)

// Linus

**Comment by boldninja** [comment]
Hey Linus,

minor text typo PRs that are not code related will only count as 1 PR, max 1 per user and won't include you in that list for additional bounties, else 2 guys could contemplate and abuse our program and just leave intentional typos and collect bounties. I'll make it more clear.

**Comment by LgLinus** [comment]
Aha, that makes sense! Thank you for the quick reply!

**Pull request merged**
