### PR TITLE
Make it possible to use custom networks

### PR DESCRIPTION
**Pull request by Nasicus**
Implemented:

- [x] Create new custom networks (auto configure)
- [x] Manage custom networks
- [x] Delete custom networks
- [x] Create profile with custom networks
- [x] Make it possible to show market data (price etc.) from custom networks

Todo:

- [x] German Translations
- [x] Better UI
- [x] Refactoring
- [x] must `wif ` and `bip32` be configurable?
   - probably not, they are both ledger related!

Optional:
- Wait until ark-ts issues are resolved, https://github.com/ArkEcosystem/ark-ts/pull/21
  - Not really required, since it works without changes

### CODE REVIEW

**Comment by Nasicus** [comment]
This one is ready for review.

So I just pushed an update which tries to make the method `findGoodPeer` better (see commit message).
I would recommend reviewing this commit separetly.

Also here are some test IPs (pm me on slack if you need an account with some tokens on it for testing):

PERSONA TEST NET:
http://5.135.75.65:4101
Nethash: b4e87739ca85f7eabf844a643930573e9a2dd9da291662e74d26962b5c3f0ed9

Blockpool
Market name: BPL   (for price chart, etc.)
Seed: http://13.56.163.57:9030
Nethash: 7bfb2815effb43592ccdd4fd0f657c082a7b318eed12f6396cc174d8578293c3

**Comment by Nasicus** [comment]
@luciorubeens 
No I thought we use modals everywhere :P didn't realize we often use pages.
Should I change it?

**Comment by luciorubeens** [comment]
I'll merge and we'll change when we have the design 👍 Very good!

**Comment by Nasicus** [comment]
Thanks just tell me in slack or here when you know it.

**Pull request merged**
