### PR TITLE
General Bug Fixes

### LINKED ISSUE #32: QR scanner not working when sending
OS: Android 5.1
Mobile wallet version: 1.0.0

Scanning a QR code doesn't work on the Send screen. I get this message:
_There was a problem scanning a QR code._

However, I have Barcode Scanner app and it worked from the first try.

And the message should be changed to:
_There was a problem scanning **the** QR code._

### PR DESCRIPTION
**Pull request by alexbarnsley**
Resolves #32

### CODE REVIEW

**Comment by luciorubeens** [comment]
Sounds good! But why the static variable in the `market-data`? 🤔 A single instance of the provider is created when starting the application

**Comment by alexbarnsley** [comment]
I found that it creates many instances 🤔 noticed it when working on the explorer too. Let me re-test with some debug and I'll screenshot if that's still the case. This did fix inconsistencies at the time

**Comment by Nasicus** [comment]
If I may explain something which you might be missing:

A new instance of an angular injectable (service) is created whenever ` providers: [ HeroService ]` is written at a component / module declaration.
This service instance is then passed to all child components of this component/module.
If you want a singleton service, you can either do this at the root-component (`app-component`)
or even in the module itself. See also [here](https://angular.io/guide/dependency-injection#ngmodule-or-component) for more details.

If this wasn't the problem or you knew that already, just ignore my comment :P

**Comment by luciorubeens** [comment]
@alexbarnsley I tried to run this branch, however I can't open any wallet and no output on the console.

**Comment by alexbarnsley** [comment]
That's weird. When I left it it was fine. I'll retry in the morning. Is it when starting from scratch or existing wallet?

I don't think I changed anything to do with wallets themselves.

I did mean to reply to this. I'll be removing the static stuff. I tested and the provider was only called once, so I'm not sure what was causing my issue

**Comment by luciorubeens** [comment]
I think you forgot to commit the `MarketNumberPipe` file.

**Comment by alexbarnsley** [comment]
I don't know what you mean Lucio. I'm sure I'm not that stupid 😅

**Comment by luciorubeens** [comment]
😆 is not here: https://github.com/ArkEcosystem/ark-mobile/tree/currency-fixes/src/pipes

**Comment by alexbarnsley** [comment]
I'm sorry, you must have me confused with someone else :trollface:

**Comment by alexbarnsley** [comment]
I'll commit it next time I'm at my laptop. I'd have carried on with this but stuff keeps coming up. It'll be in the next few hours

**Comment by alexbarnsley** [comment]
Present in my last commit for you @luciorubeens 😉  I used static here. Maybe it fixed an issue I had here so i tried it in the other Provider 🤔

**Pull request merged**
