### PR TITLE
Shorten addresses in send transaction input field

### LINKED ISSUE #106: Send transaction address field
Can you guys come up with something so I can see the whole address when I scan a QR code? Currently I have to tap on the field and select/move it so I see how the address ends. Maybe if you remove the padding, the reset (X) button and/or move the QR icon...

### PR DESCRIPTION
**Pull request by ItsANameToo**
Fixes #106 by shortening addresses when they are longer than a specified threshold. See screenshot below: 

contacts

When clicking on the input field, the full address will be shown in case you want to inspect / change it. When leaving the field, it will be shortened again

### CODE REVIEW

**Comment by Nasicus** [comment]
Well I had no doubt that you can do it yourself.

However you could probably do it much simpler by changing the `labelAttribute` field in `contacts-auto-complete.ts`.
Just introduce a new field in ` AutoCompleteContact` e.g.  `truncatedLabel`, set this field when creating autocomplete contacts & wallet labels and you're done. You can probably even just use the `TruncateMiddlePipe` class to do what you want.

**Comment by ItsANameToo** [comment]
@Nasicus Thanks, I'll take a look at your suggestions! :)

**Comment by ItsANameToo** [comment]
@Nasicus I looked into your suggestion with AutoCompleteContact, but couldn't get it to work. There were a couple of issues:

* I kept getting the error that there was no provider for `TruncateMiddlePipe` when trying to include it in the contacts-auto-complete file (seems to not work properly with an `@injectable`)

When substituting `TruncateMiddlePipe` with a local function that does the same, it was possible to show a truncated address after one was selected, but:

* When typing in your own address and moving to the next field, it wouldn't truncate as it is not selected in the autocomplete dropdown (I assume)
* When scanning an address with the QR code it didn't get truncated
* When selecting an address from the dropdown, it gets truncated, but after clicking the address field it keeps showing the truncated address (as that value is saved for the label)

To get around those issues, it most likely still requires `onBlur()` and `onFocus()` functions, so I prefer my current solution :P

**Comment by ItsANameToo** [comment]
Methods have been renamed, @alexbarnsley

**Comment by alexbarnsley** [comment]
Looking good! Nice work :+1:

**Pull request merged**
