### PR TITLE
Bulgarian translation

### PR DESCRIPTION
**Pull request by zillionn**

### CODE REVIEW

**Comment by ItsANameToo** [comment]
Don't forget to add Bulgarian to the list of available languages in `src/providers/settings-data/settings-data.ts` 😄

**Comment by alexbarnsley** [comment]
@zillionn please see @ItsANameToo's comment. You will need to do this in order for the translation to work.

**Comment by zillionn** [comment]
Done.

**Comment by alexbarnsley** [comment]
Bad news @zillionn, I just merged meaning there's now a conflict 😬

**Comment by zillionn** [comment]
You happy now... Guthub?

**Comment by alexbarnsley** [comment]
I'm happy, thanks @zillionn! :+1:

**Pull request merged**
